### ISSUE TITLE
#include directive should also accept angled brackets

### ISSUE THREAD

**Issue by nickph7** [walt-grace/glsl-plugin-idea#3] opened 2022-09-30 14:32 UTC
Greetings,

I am frequently coding shaders using THREE, which contains a lot of include statement with angled brackets, such as `#include <common>`. However, the plugin reports an error `STRING LITERAL expected, got <`. This is very unfortunate since most of the library I use uses shader chunk and this #include semantic. I believe it should behave more similar to #define, which has very loose check.

Thank you for your plugin, it is one of the best one out there.

**Comment by walt-grace** [comment] 2022-09-30 16:27
Thanks for the feedback. Should be very easy to fix. I'm planning next release for next week.

**Comment by walt-grace** [comment] 2022-10-01 15:29
Can you please provide an example?

**Comment by CodingRays** [comment] 2022-10-03 12:39
I have similar issues with the plugin. (Though in my cases its because of the shaderc `#include` directive which is basically equivalent to a c++ `#include`). It seems that the error makes auto indentation go haywire on following lines which is extremely frustrating to deal with.

**Comment by walt-grace** [comment] 2022-10-03 15:25
@CodingRays 
Reason is the that the grammar still doesn't recognise this form of #include, and formatting while the parser has errors is behaving indeed very badly (should be improved some time in the future). 
Also, it's a bit tricky cause the #include directive is actually not part of the GLSL specification at all! In general, most - if not all - directives should be equivalent to C directives and this is what I did. 
Will be released next week.

**Comment by CodingRays** [comment] 2022-10-03 16:06
Yeah i understand that this is pretty annoying thing to deal with which is also why i don't mind the error itself. I just really wish it wouldn't make working on the rest of the code a nightmare.

**Comment by walt-grace** [comment] 2022-10-03 19:28
Can you send me an example of your code? 
I want to test it before I release.

**Comment by CodingRays** [comment] 2022-10-04 10:28
```glsl
#include <something/something.glsl>

struct Test {
    uint test;
};
``` 
Here is some minimal code. There are multiple errors in the include and if you try to edit the struct auto indentation messes up.

**Comment by walt-grace** [comment] 2022-10-04 10:37
Thanks for you example. 
Ahh with an extension. I see. 

PS
I reproduced it with the wrong indentation and it's indeed very very annoying. Fix is going to be released tomorrow.

**Comment by walt-grace** [comment] 2022-10-07 17:23
@CodingRays @nickph7 
It's deployed. Hope it's all working.

**Comment by CodingRays** [comment] 2022-10-08 13:11
I have no issues with it anymore

**Closed** 2022-10-12 09:38 UTC
